[tool.poetry]
name = "projeto_pessoal"
version = "0.1.0"
description = ""
authors = ["Yago Silva <yago.santos@vocedm.com.br>"]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.34.0"
SQLAlchemy = "^2.0.38"
pydantic = "^2.10.6"
pytest = "^8.3.4"
mongomock = "^4.3.0"
mongomock-motor = "^0.0.35"
fastapi = "^0.115.8"
bson = "^0.5.10"
validate-docbr = "^1.10.0"
email-validator = "^2.2.0"
motor = "^3.7.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
