version: '3.8'
 
services:
  db:
    image: mongo:latest
    container_name: meu_banco
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Cliente_Estudos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
volumes:
  mongo_data:
 